name: "Test Monitora (Chaos)"

on:
  push:
  workflow_dispatch:

jobs:
  fast-success:
    runs-on: ubuntu-latest
    steps:
      - name: "Szybki start"
        run: echo "Zaczynamy!"
      - name: "Gotowe"
        run: echo "To było proste."

  long-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Inicjalizacja środowiska"
        run: sleep 10
      - name: "Kompilacja (udawana)"
        run: |
          echo "Kompiluję..."
          sleep 15
      - name: "Testy jednostkowe"
        run: sleep 15
      - name: "Pakowanie artefaktów"
        run: sleep 10